# SEO Values
title: Gskim Pages
tagline: tagline 한글 어떻게 나오니? ...
description: description 여기선 한글 잘 나오니? ...
url: https://gskim.github.io/pages/
twitter: https://twitter.com/zenorocha
logo: https://draculatheme.com/static/icons/pack-1/045-dracula.svg

# Google Analytics ID
google_analytics:

# GitHub Values
github:
  owner_name: Gskim
  owner_url: https://gskim.github.com/pages
  repository_url: https://github.com/gskim

show_downloads: false
show_header: false
remote_theme: "dracula/gh-pages"

sass:
    style: compressed

plugins:
  - jekyll-seo-tag
